
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: RailsScraper_production
  username: alphauser
  password: <%= ENV['RAILSSCRAPER_DATABASE_PASSWORD'] %>


 development:
  adapter: postgresql
  encoding: unicode
  database: alpha_database
  host: localhost
  pool: 5
  username: alphauser
  password: alphapassword